### PR TITLE
[CN-exec] Fix nested function ghost arguments

### LINKED ISSUE #502: [CN-exec] Incorrect instrumentation for nested function calls
If you instrument the following program with Fulminate, and run it,

```c
int f(int x)  /*@ requires true; @*/
{
        return x;
}

int g() /*@ requires cn_ghost u64 size; true; @*/
{
}

int main() {
        g(/*@ 1u64 @*/);
        f( f(1) );
                    return 0;
}
```
you will get like this:

```
$ cn instrument --exec-c-locs-mode --run bug.c
bug.c:17:22: warning: experimental keyword 'cn_ghost' (use of experimental features is discouraged)

Runtime typechecking of ghost arguments failed
************************************************************
************************ Failed at *************************
function f, file ./bug.exec.c, line 96
```

This is because the code is transformed to 
```c
 (
({
  ghost_call_site = EMPTY;
  0;
})
, f( (
({
  ghost_call_site = EMPTY;
  0;
})
, f(1)) ));
```
and after the inner function call `f(1)`, `ghost_call_site` becomes `CLEARED` even though it has to be `EMPTY`. The initialization for the outer function call takes place before the inner function call.

### PR DESCRIPTION
**Pull request by dimecon**
Fixes #502. Replaces the global array of ghost arguments and its global type by a global stack of frames where each frame is an array of ghost arguments tagged by (an enum representing) its type. This obviates the global ghost array size. Also switched to using `disable_ghost_arg_failure` to skip all ghost argument instrumentation that can yield a ghost argument failure (i.e., runtime ghost frame typechecking and ghost frame pop) when in test mode (this is a work around for PBT not yet supporting ghost arguments, which is a known, pre-existing issue #331).

### CODE REVIEW

File: bin/seqTest.ml [hunk 1]
```diff
@@ -80,6 +80,7 @@ let run_seq_tests
              ~experimental_curly_braces:false
              ~with_testing:true
              ~skip_and_only:([], [])
+             ?disable_ghost_args:(Some true)
```
Comment (rbanerjee20) [inline bin/seqTest.ml]: Might be nicer to have this be a bool rather than an option type? Either by making it a named argument via `~` or by setting a default value for `disable_ghost_args` in the definition of `run_seq_tests`

File: lib/fulminate/cn_to_ail.ml [hunk 2]
```diff
@@ -4835,16 +4834,17 @@ let rec cn_to_ail_lat_2
 
 
 let rec cn_to_ail_pre_post_aux
+          ?(disable_ghost_args = false)
           without_ownership_checking
           with_loop_leak_checks
           without_lemma_checks
+          is_lemma
```
Comment (rbanerjee20) [inline lib/fulminate/cn_to_ail.ml]: Is this parameter needed? Could we just set `disable_ghost_args` to false when `cn_to_ail_pre_post` is called from inside `cn_to_ail_lemma`?

File: lib/fulminate/fulminate.ml [hunk 3]
```diff
@@ -575,6 +576,7 @@ let main
   Records.populate_record_map filtered_instrumentation prog5;
   let executable_spec =
     generate_c_specs
+      ?disable_ghost_args:(Some disable_ghost_args)
```
Comment (rbanerjee20) [inline lib/fulminate/fulminate.ml]: in fact, making it a named argument of type bool would be cleaner as you could just write `~disable_ghost_args` everywhere

File: lib/fulminate/ownership.ml [hunk 4]
```diff
@@ -76,23 +75,18 @@ let get_ownership_global_init_stats
...
-     @ [ cn_ghost_state_init_fcall;
-         cn_ghost_stack_depth_init_fcall;
-         cn_ghost_arg_array_alloc_fcall
-       ])
+  let fcalls = [ cn_ghost_state_init_fcall; cn_ghost_stack_depth_init_fcall ] in
+  let fcalls =
+    if disable_ghost_args then
+      fcalls
+    else
+      fcalls @ [ cn_initialise_ghost_frame_stack_fcall ]
```
Comment (rbanerjee20) [inline lib/fulminate/ownership.ml]: Could you move the declaration of `cn_initialise_ghost_frame_stack_fcall` into the else branch here?

**Review by rbanerjee20 — COMMENTED** [review]
Thanks for working on this, and sorry for my delay in reviewing it. On the whole it looks good, and I've left a couple of comments.

**Comment by rbanerjee20** [comment]
Also, a question about `disable_ghost_args` mode - I know it's needed for test mode currently, but I was wondering whether not having ghost argument instrumentation maintains the validity of a spec with ghost arguments? E.g. if the CN specification for a function makes use of one of its ghost arguments, then I suppose disabling the ghost argument instrumentation means the spec is no longer valid and Fulminate will complain about a missing C variable?

File: lib/fulminate/cn_to_ail.ml (hunk 2 above)
Comment (rbanerjee20) [reply lib/fulminate/cn_to_ail.ml]: *set `disable_ghost_args` to true

**Comment by dimecon** [comment]
> Also, a question about `disable_ghost_args` mode - I know it's needed for test mode currently, but I was wondering whether not having ghost argument instrumentation maintains the validity of a spec with ghost arguments? E.g. if the CN specification for a function makes use of one of its ghost arguments, then I suppose disabling the ghost argument instrumentation means the spec is no longer valid and Fulminate will complain about a missing C variable?

Maybe there should be an error message saying that ghost arguments are currently not supported in test mode?

File: bin/seqTest.ml (hunk 1 above)
Comment (dimecon) [reply bin/seqTest.ml]: Done. You're right, it's nicer

File: lib/fulminate/cn_to_ail.ml (hunk 2 above)
Comment (dimecon) [reply lib/fulminate/cn_to_ail.ml]: It's not needed, and yes, that works

File: lib/fulminate/ownership.ml (hunk 4 above)
Comment (dimecon) [reply lib/fulminate/ownership.ml]: Done

**Comment by rbanerjee20** [comment]
> > Also, a question about `disable_ghost_args` mode - I know it's needed for test mode currently, but I was wondering whether not having ghost argument instrumentation maintains the validity of a spec with ghost arguments? E.g. if the CN specification for a function makes use of one of its ghost arguments, then I suppose disabling the ghost argument instrumentation means the spec is no longer valid and Fulminate will complain about a missing C variable?
> 
> Maybe there should be an error message saying that ghost arguments are currently not supported in test mode?

I spoke to @moratorium08 about this, and we think throwing an error in PBT when there's an instance of ghost arguments _anywhere_ in the spec is probably too restrictive. We need to discuss more with @ZippeyKeys12, but our initial understanding is that ghost arguments currently pose a problem to PBT when the function-to-be-tested contains ghost arguments in its spec, but this is not affected by whether the caller or any of the callees have ghost arguments. 

This discussion also emphasises to me that this is a separate piece of work and should be in a separate PR, so if you would be able to roll back the `disable_ghost_args` flag and leave the rest as-is, that would be great. Should be ready to merge this PR after that.

**Comment by dimecon** [comment]
> > > Also, a question about `disable_ghost_args` mode - I know it's needed for test mode currently, but I was wondering whether not having ghost argument instrumentation maintains the validity of a spec with ghost arguments? E.g. if the CN specification for a function makes use of one of its ghost arguments, then I suppose disabling the ghost argument instrumentation means the spec is no longer valid and Fulminate will complain about a missing C variable?
> > 
> > 
> > Maybe there should be an error message saying that ghost arguments are currently not supported in test mode?
> 
> I spoke to @moratorium08 about this, and we think throwing an error in PBT when there's an instance of ghost arguments _anywhere_ in the spec is probably too restrictive. We need to discuss more with @ZippeyKeys12, but our initial understanding is that ghost arguments currently pose a problem to PBT when the function-to-be-tested contains ghost arguments in its spec, but this is not affected by whether the caller or any of the callees have ghost arguments.
> 
> This discussion also emphasises to me that this is a separate piece of work and should be in a separate PR, so if you would be able to roll back the `disable_ghost_args` flag and leave the rest as-is, that would be great. Should be ready to merge this PR after that.

As we discussed elsewhere, I renamed `disable_ghost_args` to `disable_ghost_arg_failure` which is used in PBT to disable the instrumentation (runtime ghost frame type check and ghost frame pop) that can cause a ghost arg failure. This is a temporary workaround similar to the previous one. I also added back `is_lemma` to disable ghost arg instrumentation for lemmas.

**Comment by rbanerjee20** [comment]
Looks great, and thanks for making the requested changes. Happy for you to merge this!
